name: 'Start Stop HyyerCode AKS'

on:
  schedule:
    - cron: '0 14 * * *' # 2:00 PM UTC - 10:00 AM EST
    - cron: '0 5 * * *' # 5:00 AM UTC - 1:00 AM EST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_image:
    name: 'Start AKS Server'
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script - Stop AKS
      uses: azure/cli@v2
      if: github.event.schedule == '0 5 * * *'
      with:
        azcliversion: latest
        inlineScript: |
          az aks stop --name hyyercode-aks --resource-group hyyercode-rg-aks

    - name: Azure CLI script - Start AKS
      uses: azure/cli@v2
      if: github.event.schedule == '0 14 * * *'
      with:
        azcliversion: latest
        inlineScript: |
          az aks start --name hyyercode-aks --resource-group hyyercode-rg-aks